name: mafatih_yamani
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/duas.json
    - lib/data/categories.json
    - lib/data/ziyarat.json
    - lib/data/quran.json
    - lib/data/amals.json

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf

    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf

    - family: Sahel
      fonts:
        - asset: assets/fonts/Sahel.ttf

    - family: Samim
      fonts:
        - asset: assets/fonts/Samim.ttf

    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad.ttf

    